# Generated by Django 5.1.4 on 2025-01-31 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título de la canción')),
                ('nombre_banda', models.CharField(max_length=200, verbose_name='Nombre de la banda')),
                ('genero', models.CharField(choices=[('ROCK', 'Rock'), ('POP', 'Pop'), ('CUMBIA', 'Cumbia'), ('BALADA', 'Balada'), ('OTRO', 'Otro')], max_length=50, verbose_name='Género musical')),
                ('letra', models.FileField(blank=True, null=True, upload_to='letras/', verbose_name='Archivo de letra')),
            ],
            options={
                'verbose_name': 'Canción',
                'verbose_name_plural': 'Canciones',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del evento')),
                ('descripcion', models.TextField(verbose_name='Descripción del evento')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha', models.DateField(verbose_name='Fecha del evento')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título de la compra')),
                ('descripcion', models.TextField(verbose_name='Descripción de la compra')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('completado', models.BooleanField(default=False, verbose_name='Completado')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
            },
        ),
        migrations.CreateModel(
            name='Ensayo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha del ensayo')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observación')),
                ('cancion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ensayos', to='organizer.cancion')),
            ],
            options={
                'verbose_name': 'Ensayo',
                'verbose_name_plural': 'Ensayos',
            },
        ),
        migrations.CreateModel(
            name='Grabacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='grabaciones/', verbose_name='Archivo de grabación (audio/video)')),
                ('cancion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grabaciones', to='organizer.cancion')),
            ],
        ),
        migrations.CreateModel(
            name='GrabacionEnsayo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='ensayos/grabaciones/', verbose_name='Archivo de grabación (audio/video)')),
                ('ensayo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grabaciones', to='organizer.ensayo')),
            ],
        ),
        migrations.CreateModel(
            name='LinkVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='Link de video de referencia')),
                ('cancion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_video', to='organizer.cancion')),
            ],
        ),
        migrations.CreateModel(
            name='MultimediaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='eventos/multimedia/', verbose_name='Archivo multimedia')),
                ('tipo', models.CharField(choices=[('IMAGEN', 'Imagen'), ('VIDEO', 'Video'), ('AUDIO', 'Audio')], max_length=10, verbose_name='Tipo de multimedia')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multimedia', to='organizer.evento')),
            ],
        ),
        migrations.CreateModel(
            name='Tablatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='tablaturas/', verbose_name='Archivo de tablatura')),
                ('cancion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tablaturas', to='organizer.cancion')),
            ],
        ),
    ]
